version: '3.8'

services:
  nuxt:
    build:
      context: ./nuxt
    ports:
      - "3000:3000"
    depends_on:
      - postgres
    environment:
      - API_URL=http://django:8000  # API Django dla Nuxt.js

  django:
    build:
      context: ./back
    ports:
      - "8000:8080"
    depends_on:
      - postgres
    environment:
      - DB_HOST=postgres
      - DB_NAME=mydatabase
      - DB_USER=myuser
      - DB_PASSWORD=mypassword
    volumes:
      - ./back:/app

  postgres:
    image: postgres:13
    volumes:
      - ./postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      - POSTGRES_DB=mydatabase
      - POSTGRES_USER=myuser
      - POSTGRES_PASSWORD=mypassword
    ports:
      - "5432:5432"
