version: '3.8'

services:
  db:
    image: postgres:17.4
    restart: always
    environment:
      POSTGRES_USER: .
      POSTGRES_PASSWORD: .
      POSTGRES_DB: .
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    depends_on:
      - db
    ports:
      - "8000:8080"

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    depends_on:
      - backend
    ports:
      - "3000:3000"

volumes:
  postgres_data:
