# Pobieramy oficjalny obraz Pythona
FROM python:3.9

# Ustawiamy katalog roboczy
WORKDIR /app

# Kopiujemy pliki zależności
COPY requirements.txt .

# Instalujemy zależności
RUN pip install -r requirements.txt

# Kopiujemy resztę aplikacji
COPY . .

# Ustawiamy zmienną środowiskową dla aplikacji
ENV PYTHONUNBUFFERED 1

# Uruchamiamy serwer Django
CMD ["python", "manage.py", "runserver", "0.0.0.0:8000"]
