# Pobieramy oficjalny obraz Node.js
FROM node:18

# Ustawiamy katalog roboczy
WORKDIR /app

# Kopiujemy package.json i package-lock.json do kontenera
COPY package*.json ./

# Instalujemy zależności
RUN npm install

# Kopiujemy resztę aplikacji
COPY . .

# Budujemy aplikację Nuxt.js
RUN npm run build

# Uruchamiamy serwer Nuxt.js
CMD ["npm", "run", "dev"]
